### ISSUE TITLE
PS Arena

### ISSUE THREAD

**Issue by MarioAugustoPereira** [rafael-esper/Phantasy#2]
No modo arena me deparei com alguns bugs:

1. Quando escolhendo recompensa o menu consegue ser exibido e navegado usando o shift, porém se selecionar qualquer opção ele registra a recompensa que estava selecionada antes.

2. Quando em batalha, já após a batalha com os esqueletos, num combate contra o mostro do pântano na lava, o jogo saiu e mostrou a tela de título junto com os sprites dos mostros que estava lutando.

3. A música de combate, em batalhas mais extensas para de tocar após algum tempo e volta no próximo combate

**Comment by rafael-esper** [comment]
Finalmente, o problema do PSArena foi resolvido. Era relacionado ao uso de pistolas ou raios. 
Finally, the PSArena problem was solved. It was related to the use of guns or thunders.
