### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by duduric** [rafael-esper/Phantasy#4]
Hi, I have some problems with sound in both my operating systems (Windows 8.1 , ArchLinux)
It works OK for some random amount of time, then all the sounds stop and I start getting this exception a lot of times:

javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

It gets rather unstable after this, and randomly crashes to the desktop. I am mainly testing in the Arena.

**Comment by rafael-esper** [comment]
The problem was solved (sorry for the long time). I could reproduce it, and it was fixed. Tested in my Ubuntu Linux.
