### ISSUE TITLE
Lassic / Raios e Pistolas

### ISSUE THREAD

**Issue by silviorobertosanchez** [rafael-esper/Phantasy#7]
Olá Rafael, estou jogando e tenho problemas sempre quando uso Pistolas, ou Raios. Posso ver que são rotinas que atacam todos os inimigos, a batalha sai. Isso acontece também quando sou atacado por raios, no caso de Lassic que só ataca com raios, a batalha sempre da uns bugs quando ele finaliza seu primeiro ataque.

**Comment by rafael-esper** [comment]
Ok, obrigado por reportar o problema. Vou investigar.

Em 16 de maio de 2015 13:15, silviorobertosanchez <notifications@github.com>
escreveu:

**Comment by silviorobertosanchez** [comment]
Rafael, hoje tive a oportunidade de fazer o teste aqui onde trabalho e funcionou perfeitamente, o erro ocorre apenas rodando em casa onde uso Win 8.1 em um note de 64bits. Não sei se tem algo haver mas no XP 32bits funcionou perfeitamente.

**Comment by rafael-esper** [comment]
Obrigado pela ajuda na investigação. Vou testar com o meu Linux 64 bits.
Esse problema não ocorreu anteriormente em um Windows 7 64 bits que testei.
Talvez seja algo relacionado com a versão do Java ou com o som (pois nesse
caso os sons são repetidos, e podem ser modulados sobrepostos).

Abs,
Rafael

Em 18 de maio de 2015 09:51, silviorobertosanchez <notifications@github.com>
escreveu:

**Comment by silviorobertosanchez** [comment]
Te mandei um email com o print do erro

**Comment by GianMenon** [comment]
Estou tendo o mesmo problema. Quando os raios ou ataques de pistola acertam o ultimo alvo, sai da batalha. Inclusive nas cavernas, onde ainda as vezes o jogo sai da parte em 1ª pessoa e nos vemos nos mapas das cavernas como no mapa principal.

**Comment by rafael-esper** [comment]
Obrigado pelo retorno. Preciso ver isso com urgência!


Em 15 de junho de 2015 19:52, GianMenon <notifications@github.com> escreveu:

**Comment by GianMenon** [comment]
Por sorte conseguir resolver o problema, mas náo do jeito que deveria ser.
Eu precisei fazer downgrade na minha versáo do java por causa do programa gerenciador do meu access point, que não funciona com java atualizado.
Depois de instalar o java 6, não encontrei mais os erros dos projéteis no jogo.
Espero que essa informação ajude.

**Comment by rafael-esper** [comment]
O problema relacionado a raios foi finalmente resolvido. Se puderem testar, agradeço!!
